In [9]:
import pandas as pd
import hvplot
import hvplot.pandas as hvp

In [10]:
import calendar
year = 2022

# list of month names using calendar module
list_of_months = list(calendar.month_name)[1:]

list_of_months

['January',
 'February',
 'March',
 'April',
 'May',
 'June',
 'July',
 'August',
 'September',
 'October',
 'November',
 'December']

In [11]:
list_df = []

january = pd.read_csv(f'2022/January.csv')

january

,TRN_PK,StartTime,EndTime,ReceiptNumber,CustomerAccount,Department,DiscountAmount,TransactionTotal,NetSales,RedemptionCount,TLI_Quantity,TLI_Amount,Month
0,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,NaN,-0.30,91.16,91.16,1.0,1.0,-0.30,January 2022
1,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,NaN,-0.27,91.16,91.16,1.0,1.0,-0.27,January 2022
2,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,NaN,-0.24,91.16,91.16,1.0,1.0,-0.24,January 2022
3,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,NaN,-0.24,91.16,91.16,1.0,1.0,-0.24,January 2022
4,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,NaN,-0.24,91.16,91.16,1.0,1.0,-0.24,January 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76392,1078700,2022-01-31 20:49:59.193,2022-01-31 20:52:08.189,126027,44411100001,NaN,-0.15,92.30,92.30,1.0,1.0,-0.15,January 2022
76393,1078700,2022-01-31 20:49:59.193,2022-01-31 20:52:08.189,126027,44411100001,NaN,-0.15,92.30,92.30,1.0,1.0,-0.15,January 2022
76394,1078700,2022-01-31 20:49:59.193,2022-01-31 20:52:08.189,126027,44411100001,NaN,-0.15,92.30,92.30,1.0,1.0,-0.15,January 2022
76395,1078700,2022-01-31 20:49:59.193,2022-01-31 20:52:08.189,126027,44411100001,NaN,-0.14,92.30,92.30,1.0,1.0,-0.14,January 2022
76396,1078700,2022-01-31 20:49:59.193,2022-01-31 20:52:08.189,126027,44411100001,NaN,-0.10,92.30,92.30,1.0,1.0,-0.10,January 2022

In [12]:


for month in list_of_months:
    month_df = pd.read_csv(f'{year}\{month}.csv')
    month_df['month'] = month
    list_df.append(month_df)

year_df = pd.concat(list_df)

C:\Users\adossantos\AppData\Local\Temp\ipykernel_19900\1899590796.py:2: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  month_df = pd.read_csv(f'{year}\{month}.csv')
C:\Users\adossantos\AppData\Local\Temp\ipykernel_19900\1899590796.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  month_df = pd.read_csv(f'{year}\{month}.csv')
C:\Users\adossantos\AppData\Local\Temp\ipykernel_19900\1899590796.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  month_df = pd.read_csv(f'{year}\{month}.csv')
C:\Users\adossantos\AppData\Local\Temp\ipykernel_19900\1899590796.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  month_df = pd.read_csv(f'{year}\{month}.csv')

In [13]:
# year_df.count()

In [14]:
# year_df.dtypes

In [15]:
# year_df = pd.read_csv('monthly_2023.csv')

In [16]:
print(year_df.count())

print(year_df.dtypes)

TRN_PK              1878684
StartTime           1878684
EndTime             1878684
ReceiptNumber       1878684
CustomerAccount     1878682
Department          1026882
DiscountAmount      1878684
TransactionTotal    1878684
NetSales            1878684
RedemptionCount     1878684
TLI_Quantity        1878684
TLI_Amount          1878684
Month               1878684
month               1878684
dtype: int64
TRN_PK                int64
StartTime            object
EndTime              object
ReceiptNumber         int64
CustomerAccount      object
Department           object
DiscountAmount      float64
TransactionTotal    float64
NetSales            float64
RedemptionCount     float64
TLI_Quantity        float64
TLI_Amount          float64
Month                object
month                object
dtype: object

In [17]:
year_df['StartTime'] = pd.to_datetime(year_df['StartTime'])

year_df['EndTime'] = pd.to_datetime(year_df['EndTime'])

In [18]:
year_df = year_df.drop(['Department'],axis=1)

year_df.head(10)

,TRN_PK,StartTime,EndTime,ReceiptNumber,CustomerAccount,DiscountAmount,TransactionTotal,NetSales,RedemptionCount,TLI_Quantity,TLI_Amount,Month,month
0,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,-0.30,91.16,91.16,1.0,1.0,-0.30,January 2022,January
1,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,-0.27,91.16,91.16,1.0,1.0,-0.27,January 2022,January
2,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,-0.24,91.16,91.16,1.0,1.0,-0.24,January 2022,January
3,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,-0.24,91.16,91.16,1.0,1.0,-0.24,January 2022,January
4,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,-0.24,91.16,91.16,1.0,1.0,-0.24,January 2022,January
5,1052052,2022-01-19 09:38:55.813,2022-01-19 09:41:19.542,123039,44411100001,-0.24,91.16,91.16,1.0,1.0,-0.24,January 2022,January
6,1052254,2022-01-19 10:58:01.471,2022-01-19 10:59:03.537,121487,44411100001,-0.84,59.95,59.95,1.0,1.0,-0.84,January 2022,January
7,1052254,2022-01-19 10:58:01.471,2022-01-19 10:59:03.537,121487,44411100001,-0.74,59.95,59.95,1.0,1.0,-0.74,January 2022,January
8,1052254,2022-01-19 10:58:01.471,2022-01-19 10:59:03.537,121487,44411100001,-0.72,59.95,59.95,1.0,1.0,-0.72,January 2022,January
9,1052254,2022-01-19 10:58:01.471,2022-01-19 10:59:03.537,121487,44411100001,-0.60,59.95,59.95,1.0,1.0,-0.60,January 2022,January

In [19]:

year_df_grouped = year_df.groupby('TRN_PK').agg(
    TotalDiscountAmount = ('DiscountAmount','sum'),
    Start = ('StartTime', 'last'),
    End = ('EndTime', 'last'),
    ReceiptNumber = ('ReceiptNumber', 'first'),
    CustomerAccount = ('CustomerAccount','first'),
    TransactionTotal = ('TransactionTotal', 'first'),
    NetSales = ('NetSales', 'first'),
    TotalRedemptionCount = ('RedemptionCount', 'sum'),
    TotalTLIqty = ('TLI_Quantity','sum'),
    TotalTLIamt = ('TLI_Amount','sum'),
    Month = ('month','first')
).reset_index()

In [20]:
year_df_grouped.tail(5)

,TRN_PK,TotalDiscountAmount,Start,End,ReceiptNumber,CustomerAccount,TransactionTotal,NetSales,TotalRedemptionCount,TotalTLIqty,TotalTLIamt,Month
140258,1735119,-40.52,2022-12-31 10:43:24.263,2022-12-31 10:46:55.353,218362,44411100001,364.75,364.75,70.0,70.0,-40.52,December
140259,1735121,-4.77,2022-12-31 10:46:05.078,2022-12-31 10:47:27.363,217948,44411100001,42.86,42.86,8.0,8.0,-4.77,December
140260,1735122,-16.07,2022-12-31 10:44:37.466,2022-12-31 10:47:36.134,217659,4159993458,145.69,145.69,33.0,33.0,-15.38,December
140261,1735123,-1.66,2022-12-31 10:47:15.758,2022-12-31 10:47:54.486,218363,44411100001,14.92,14.92,1.0,1.0,-1.66,December
140262,1735125,-17.87,2022-12-31 10:47:34.410,2022-12-31 10:49:36.382,217949,4156010500,162.21,162.21,36.0,36.0,-14.87,December

In [21]:
year_df_grouped = year_df_grouped.assign(
    EndDate=year_df_grouped["End"].dt.date, 
    EndTime=year_df_grouped["End"].dt.time
)

In [22]:
year_df_grouped['TotalDiscountAmount'] = year_df_grouped['TotalDiscountAmount']* -1

In [23]:
year_df_grouped.tail(5)

,TRN_PK,TotalDiscountAmount,Start,End,ReceiptNumber,CustomerAccount,TransactionTotal,NetSales,TotalRedemptionCount,TotalTLIqty,TotalTLIamt,Month,EndDate,EndTime
140258,1735119,40.52,2022-12-31 10:43:24.263,2022-12-31 10:46:55.353,218362,44411100001,364.75,364.75,70.0,70.0,-40.52,December,2022-12-31,10:46:55.353000
140259,1735121,4.77,2022-12-31 10:46:05.078,2022-12-31 10:47:27.363,217948,44411100001,42.86,42.86,8.0,8.0,-4.77,December,2022-12-31,10:47:27.363000
140260,1735122,16.07,2022-12-31 10:44:37.466,2022-12-31 10:47:36.134,217659,4159993458,145.69,145.69,33.0,33.0,-15.38,December,2022-12-31,10:47:36.134000
140261,1735123,1.66,2022-12-31 10:47:15.758,2022-12-31 10:47:54.486,218363,44411100001,14.92,14.92,1.0,1.0,-1.66,December,2022-12-31,10:47:54.486000
140262,1735125,17.87,2022-12-31 10:47:34.410,2022-12-31 10:49:36.382,217949,4156010500,162.21,162.21,36.0,36.0,-14.87,December,2022-12-31,10:49:36.382000

In [24]:

# year_df_grouped.to_csv(f'year_df_grouped_{year}.csv', index=False)

In [25]:
by_day = year_df_grouped.groupby('EndDate').agg(
    CustomerCount = ('TRN_PK','count'),
    TotalDiscountAmount = ('TotalDiscountAmount','sum'),
    CustomerAccount = ('CustomerAccount','count'),
    TransactionTotal = ('TransactionTotal', 'sum'),
    TotalRedemptionCount = ('TotalRedemptionCount', 'sum'),
    Month = ('Month','first')
).reset_index()

by_day['year'] = year
by_day.head(5)

,EndDate,CustomerCount,TotalDiscountAmount,CustomerAccount,TransactionTotal,TotalRedemptionCount,Month,year
0,2022-01-19,462,3513.99,462,35656.30,6296.0,January,2022
1,2022-01-20,401,2873.87,401,27359.02,5293.0,January,2022
2,2022-01-21,403,3271.01,403,31902.28,5750.0,January,2022
3,2022-01-22,399,3503.16,399,33790.51,6269.0,January,2022
4,2022-01-23,355,2847.19,355,28219.01,5178.0,January,2022

In [26]:
# by_day.to_csv(f'by_day_{year}.csv', index=False)